#include <iostream>

using namespace std;

class A
{
    public:
    int a;
    
    void setdata( int a)
    {
        this-> a = a; 
    }

    void getdata()
    {
        cout<<"value is :"<<a<<endl;
    }

};

using namespace std;

int main()
{ 
    //A a1;
    A *ptr = new A[3];// this alloacate memory for 3 instances(i.e objects) of class A in form of pointer

    (ptr[0]).setdata(2);
    (ptr[0]).getdata();

    (ptr[1]).setdata(2);
    (ptr[1]).getdata();
    //dereferencing is not needed why we acces array elements generated by new keyword
    //array subscript operator implicitly deferenced.
    //instead of array we can also use pointer airthmetic
    (*(ptr+2)).setdata(2);
    (*(ptr+2)).getdata();

return 0;

}